### ISSUE TITLE
Feedback on first submission

### ISSUE THREAD

**Issue by Anisha7** [fchikwekwe/CS-1-3-Algorithms-Data-Structures#1]
Good job on completing the first submission! Here’s what you can do to improve:

- Good job annotating time complexities for your string function. Do the same for space complexity. (How much space is being used/allocated by your functions?)
- Insert_at_index method for linked list does not pass unit tests currently. Try to debug this and get it to work. Use print statements, custom tests, and unit tests for direction/help in figuring out the issue. Feel free to reach out/use office hours to get help if you feel stuck!

**Comment by fchikwekwe** [comment]
Thanks for the feedback. I've implemented the requested changes. Please let me know if anything else if required.
