### ISSUE TITLE
Feedback on submission 2

### ISSUE THREAD

**Issue by Anisha7** [fchikwekwe/CS-1-3-Algorithms-Data-Structures#2]
Good job on completing the second coding challenge. Some bugs I noticed that could be fixed:
- Typo in your queue.py file: length() method for LinkedQueue somehow turned into Lh(). It should be called length, to pass all tests. I assume its just a typo.
- Typo in set’s __str__ function. Random space between the hash table.keys() call… run your tests before submitting to make sure there are no typos.

**Comment by fchikwekwe** [comment]
Thank you for the feedback @Anisha7! Fixed the LinkedQueue length method. 

Unfortunately, since sets are unordered, I wasn't able to find a consistent way to testing that **str** method. Maybe I'll come by office hours and see if we can try to find a better way. Thanks!
